version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    volumes:        #挂载当前的data目录到容器默认mysql存储目录
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/docker/source:/docker-entrypoint-initdb.d
    environment:                        #环境变量
      MYSQL_USER: qzr
      MYSQL_PASS: 888888
      MYSQL_ROOT_PASSWORD: 888888    #mysql的root密码
      MYSQL_DATABASE: page     #mysql的初始化数据库
    ports:
      - "3306:3306"
    networks:
      - end

  app:
    container_name: app
    restart: always
    image: constq/page-blog:back-v1
    ports: 
      - "7001:7001"
    depends_on:
      - mysql
    networks:
      - front
      - end

  web:
    container_name: web
    restart: always
    image: constq/page-blog:front-v1
    ports:
      - "9009:9009"
    networks:
      - front

networks:
  front:
  end: